# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

NumPy no pertenece al _core_ de Python y es por eso que debemos importarlo para poder usarlo.

Para importar una libreria en Python se usa la siguiente sintaxis:
    
`import libreria as alias`

Para importar una funcion en particular de un modulo o libreria, utilizamos la sintaxis:
    
`from libreria import funcion`

Como convencion, cuando se importa `numpy` se le asigna el alias `np`. Pero esto no es obligatorio, solo me facilita muchas veces la escritura del codigo.

In [ ]:
#Importar numpy
import numpy as np

De ahora en mas para utilizar una función de Numpy solo tengo que usar `np` y luego llamar función. Por ejemplo, si quiero llamar la función `.mean()`, debo escribir: `np.mean()`.

Comenzemos a ver que funciones se pueden utilizar en NumPy.

- `.array()`

Esta función me permite crear un array. Es posible crear arrays a partir de listas.

In [ ]:
#creo un array
arreglo = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
creo = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [ ]:
la_lista = [10, 20, 30, 13, 14, 40, 16, 17, 18, 50]
tu_array = np.array(la_lista)
print(tu_array)
type(tu_array)


[10 20 30 13 14 40 16 17 18 50]


numpy.ndarray

In [ ]:
#crea una lista llamada mi_lista que contenga 10 numeros

mi_lista = [110,120,130,140,150,160,170,180,190]

#Ahora transforma tu lista en un array usando np.array y asignalo a la variable mi_array

mi_array = np.array(mi_lista)

#Imprimi mi_array
print(mi_array)

[110 120 130 140 150 160 170 180 190]


Podemos usar `type` para obtener el tipo de estructura de datos que estamos trabajando.

In [ ]:
#Aplica type sobre mi_array para mostrar que tipo de estructura de datos es
type(mi_array)


numpy.ndarray

Los arrays y las listas se comportan diferente frente operaciones matematicas con números.

In [ ]:
dos = [2]
print(la_lista + dos)  # incorpora la lista y agrega un dato mas en el array
# print(la_lista + 2) No se puede sumar un numero asi a una lista

[10, 20, 30, 13, 14, 40, 16, 17, 18, 50, 2]


In [ ]:
#Corre el siguiente codigo
print(mi_array+2) # A MI LISTA NO PUEDO AGREGAR O CONTATENAR UN 2 %% [markdown]
# No es posible sumar un numero a cada uno de los elementos de una lista. Sin
# embargo, esto funciona distinto en Numpy. %%
   #observacciones nancy
#en este caso creo el array para usar la herramienta de numpy, es esta caso
#suma todos los elementos del array +2 de cada elemento del array


[112 122 132 142 152 162 172 182 192]


No es posible sumar un numero a cada uno de los elementos de una lista. Sin embargo, esto funciona distinto en Numpy.

In [ ]:
la_lista2 = [i + 2 for i in la_lista]
print(la_lista2)
print(la_lista2 * 2)

[12, 22, 32, 15, 16, 42, 18, 19, 20, 52]
[12, 22, 32, 15, 16, 42, 18, 19, 20, 52, 12, 22, 32, 15, 16, 42, 18, 19, 20, 52]


In [ ]:
#Suma 2 a cada elemento de mi_array
mi_lista2 = [i + 2 for i in mi_lista]

print(mi_lista2)

[112, 122, 132, 142, 152, 162, 172, 182, 192]


El comportamiento tambien es distinto para la operacion de multiplicacion.

In [ ]:
#Corre el siguiente codigo y fijate que pasa
print(mi_lista*2)

#lo que hace que lista , los elementos se multipliquen 2 veces, por lo tanto
#lo que hace es crear 2 veces la lista, los datos no los multiplica

[110, 120, 130, 140, 150, 160, 170, 180, 190, 110, 120, 130, 140, 150, 160, 170, 180, 190]


In [ ]:
la_lista3 = [i * 2 for i in la_lista]
print(la_lista3)

[20, 40, 60, 26, 28, 80, 32, 34, 36, 100]


In [ ]:
#Ahora multiplica por dos cada elemento de mi_array

mi_lista3 =  [i * 2 for i in mi_array]

print(mi_lista3)

[np.int64(220), np.int64(240), np.int64(260), np.int64(280), np.int64(300), np.int64(320), np.int64(340), np.int64(360), np.int64(380)]


Los arrays y las listas se comportan diferente frente a operaciones con otros arrays/listas

In [ ]:
#Corre el siguiente codigo
lista1 = [1, 2, 3, 4, 5]
lista2 = [5, 4, 3, 2, 1]

arr1 = np.array(lista1)
arr2 = np.array(lista2)

In [ ]:
liste1 = [1, 2, 3, 4, 5]
liste2 = [5, 4, 3, 2, 1]
liste1 + liste2


[1, 2, 3, 4, 5, 5, 4, 3, 2, 1]

In [ ]:
#Concatena las dos listas
lista1 + lista2

[1, 2, 3, 4, 5, 5, 4, 3, 2, 1]

In [ ]:
liste1 = [1, 2, 3, 4, 5]
liste2 = [5, 4, 3, 2, 1]
i=liste1 + liste2
print(i)
liste3 = [i for i in liste1 for j in liste2]
liste3.append(i for i in liste1 for j in liste2)
print(liste3)
# esto suma el primer elemento de cada lista
print(liste3)

[1, 2, 3, 4, 5, 5, 4, 3, 2, 1]
[1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, <generator object <genexpr> at 0x79f870365e00>]
[1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, <generator object <genexpr> at 0x79f870365e00>]


In [ ]:
#Suma los elementos de los dos arrays

lista3 = []
for i in lista1:
  for j in lista2:
    lista3.append(i + j)
print(lista3)
print(lista1+lista2)

lista1 = [1,2,3,4]
lista2 = [9,2,3,4]
array1 = np.array(lista1)
array2 = np.array(lista2)

print(array1 + array2)

[6, 5, 4, 3, 2, 7, 6, 5, 4, 3, 8, 7, 6, 5, 4, 9, 8, 7, 6, 5, 10, 9, 8, 7, 6]
[1, 2, 3, 4, 5, 5, 4, 3, 2, 1]
[10  4  6  8]


In [ ]:
#Multiplica los elementos de cada arreglo
lista=[]
for i in array1:
 for j in array2:
  arreglo_f = array1 * array2
print(arreglo_f)

[ 9  4  9 16]


In [ ]:
#lista=[]
for i in array1:
 for j in array2:
  arreglo_f = array1 - array2
print(arreglo_f)

[-8  0  0  0]


In [ ]:
#Dividi los dos arrays
lista=[]
for i in array1:
 for j in array2:
  arreglo_f = array1 // array2
print(arreglo_f)

[0 1 1 1]


In [ ]:
#Eleva el array1 al array2
lista=[]
for i in array1:
 for j in array2:
  arreglo_f = array1 ** array2
print(arreglo_f)

[  1   4  27 256]


Para acceder a los elementos de los arrays de una dimension se utilizan los indices como las listas.

In [ ]:
#Corre el siguiente codigo
print(lista1[0], arr1[0])

1 1


In [ ]:
#Obtene el 3er elemento de arr1
print(lista1[2], arr1[2])

3 3


In [ ]:
#Obtene el 5to elemento de arr2
print (arr2[4])

1


In [ ]:
#Obtene el ultimo elemento de arr1
print(arr1[-1])

5


Asi tambien obtenemos una porción del array de la misma manera que obtenemos una parte de una lista. A su vez podemos reasignar nuevos valores a una porción del array.

In [ ]:
#Corre el siguiente codigo
# Array1 tiene 4 elementos [0:3]
lista1 = [1,2,3,4]
lista2 = [9,2,3,4]
array1 = np.array(lista1)
array2 = np.array(lista2)

array1[1:4] = [22, 23, 24]    # Acordarse que tomamos hasta N-1 entonces si queremos 3 numeros debemos poner 1:4 en este caso

print(array1)

[ 1 22 23 24]


In [ ]:
#Imprimi el arr1
print(arr1)

[1 2 3 4 5]


## Arreglos multidimensionales

Las listas son cadenas unidimensionales de elementos. Los arreglos pueden ser multidimensionales. Para comprender mejor que son, miremos el siguiente ejemplo:

In [ ]:
#Corre el siguiente codigo
lista = [[0, 1, 3], [3, 4, 5]]
arr2d = np.array(lista)
print(arr2d)

[[0 1 3]
 [3 4 5]]


In [ ]:
#Veamos cuantas dimensiones tiene el array
print(arr2d.ndim) # Dos filas

2


In [ ]:
#Veamos cuantos elementos tiene el array
print(arr2d.size) # 6 elementos

6


In [ ]:
#Arma ahora un array de 3 dimensiones.
coso = [[[2,7,6],[1,2,5],[10,20,30]]]
arr3d = np.array(coso)
print(arr3d)

[[[ 2  7  6]
  [ 1  2  5]
  [10 20 30]]]


In [ ]:
#Chequea usando ndim que efectivamente tenga tres dimensiones
print(arr3d.ndim)

3


**¿Como accedemos entonces a un array de mas de una dimension?**

In [ ]:
#definamos un nuevo array
lista2 = [[0, 1, 3], [3, 4, 5], [9, 10, 4], [2, 5, 6]]
nuevo_array = np.array(lista2)
print(nuevo_array)

[[ 0  1  3]
 [ 3  4  5]
 [ 9 10  4]
 [ 2  5  6]]


¿Cuantas dimensiones tiene el array `nuevo_array`? Comprobalo usando `ndim`.

In [ ]:
#Dimensiones de nuevo_array
print(nuevo_array.ndim)

2


In [ ]:
#Mostra nuevo_array
print(nuevo_array)

[[ 0  1  3]
 [ 3  4  5]
 [ 9 10  4]
 [ 2  5  6]]


Si para un array de 1 dimension, usabamos un indice, para un array de n dimensiones tenemos que usar n indices. En el caso de 2 dimensiones, usaremos 2 indices. El primero indica la fila y el segundo la columna.

In [ ]:
#Corre el siguiente codigo
print(nuevo_array[0, 1])

1


In [ ]:
#Accede al tercer elemento de la segunda fila de nuevo_array
print(nuevo_array[1,2])

5


In [ ]:
#Accede al cuarto elemento de la segunda columna de nuevo_array
print(nuevo_array[3,2])

6


In [ ]:
#Accedo a toda la segunda columna
nuevo_array[:,1]

array([ 1,  4, 10,  5])

In [ ]:
# Accede a un subarray que vaya desde el segundo elemento de la primer columna hasta el cuarto elemento de la tercer
# columna de nuevo_array

print(nuevo_array[1:4 ,0:3])


[[ 3  4  5]
 [ 9 10  4]
 [ 2  5  6]]


In [ ]:
# Accede a un subarray que vaya desde el primer elemento de la segunda fila hasta el segundo elemento de la cuarta
#fila de nuevo_array

print(nuevo_array[1:5 , 0:2])

[[ 3  4]
 [ 9 10]
 [ 2  5]]


## Creación de arreglos

- **np.zeros(shape, dtype, order)**: Crea un array con todos ceros en sus posiciones

In [ ]:
#Corre el siguiente codigo
print(np.zeros((2, 2, 2)))

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


- **np.ones(shape, dtype, order)**: Crea un array con todos unos en sus posiciones

In [ ]:
#Corre el siguiente codigo
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


- **np.random.rand(d0, d1, ..., dn)**: Genera un array con valores al azar con una distribución `[0, 1)` y segun las dimensiones pasada como argumento.

In [ ]:
#Genera un array con valores al azar
print(np.random.randn(10))

[-1.56543551  1.64044472  1.03350947 -0.4380835  -0.44321423 -0.45249691
  0.01000077 -0.37704675 -0.70589452 -1.38329754]


- **np.random.randint(low, high, size)**: Devuelve un array con enteros al azar. Cuando se especifica un solo entero como argumento este entero es entendido como el mayor valor que ese numero random puede tomar. Si se pasan dos, uno es el menor valor y el otro es el mayor valor. Con size se le puede decir que dimensiones tiene el array. Si no le paso ningun valor, devolvera solo un numero entero.

In [ ]:
#Genera un array con enteros al azar
np.random.randint(5)




2

- **np.arange([start, ]stop, [step, ])**: Devuelve numero simetricamente distribuidos segun los valores datos. El primer valor es el comienzo, el segundo el final y el tercero representa cada cuanto queremos esos valores.

In [ ]:
#Corre esta linea de codigo y comprende como funciona np.arange
np.arange(2, 16, 2)

array([ 2,  4,  6,  8, 10, 12, 14])

## Funciones estadisticas

NumPy nos facilita varias funciones que nos permitiran obtener algunos parametros estadisticos de nuestros arrays. Veamos cuales son estas funciones.

In [ ]:
#Volvamos a ver como era nuestro array nuevo_array
print(nuevo_array)

[[ 0  1  3]
 [ 3  4  5]
 [ 9 10  4]
 [ 2  5  6]]


- `np.mean()`: Media o Promedio.

In [ ]:
#usa la funcion mean para obtener el promedio de los valores en nuevo_array


np.mean(nuevo_array)

np.float64(4.333333333333333)

- `np.var()`: Devuelve la dispersión de los valores alrededor de la media

In [ ]:
#usa la funcion var para obtener la varianza de los valores en nuevo_array
np.var(nuevo_array)

np.float64(8.055555555555557)

- `np.sum()`: devuelve la suma de todos los valores en el array.
- `np.min()`: devuelve el menor valor en el array
- `np.max()`: devuelve el maximo valor en el array

In [ ]:
#Muestra la suma de los valores en nuevo_array
print(np.sum(nuevo_array))

#Muestra el minimo y maximo valor en nuevo array

print(np.min(nuevo_array))
print(np.max(nuevo_array))

52
0
10
